import Form from "react-bootstrap/Form";

const SelectPaises = ({onPaisChange}) => {
  const countries = [
    { pais: "Argentina", code: "ar" },
    { pais: "Afghanistan", code: "af" },
    { pais: "Albania", code: "al" },
    { pais: "Algeria", code: "dz" },
    { pais: "Andorra", code: "ad" },
    { pais: "Angola", code: "ao" }, 
    { pais: "Armenia", code: "am" },
    { pais: "Australia", code: "au" },
    { pais: "Austria", code: "at" },
    { pais: "Azerbaijan", code: "az" },
    { pais: "Bahamas", code: "bs" },
    { pais: "Bahrain", code: "bh" },
    { pais: "Bangladesh", code: "bd" },
    { pais: "Barbados", code: "bb" },
    { pais: "Belarus", code: "by" },
    { pais: "Belgium", code: "be" },
    { pais: "Belize", code: "bz" },
    { pais: "Benin", code: "bj" },
    { pais: "Bermuda", code: "bm" },
    { pais: "Bhutan", code: "bt" },
    { pais: "Bolivia", code: "bo" },
    { pais: "Bosnia And Herzegovina", code: "ba" },
    { pais: "Botswana", code: "bw" },
    { pais: "Brazil", code: "br" },
    { pais: "Brunei", code: "bn" },
    { pais: "Bulgaria", code: "bg" },
    { pais: "Burkina Faso", code: "bf" },
    { pais: "Burundi", code: "bi" },
    { pais: "Cambodia", code: "kh" },
    { pais: "Cameroon", code: "cm" },
    { pais: "Canada", code: "ca" },
    { pais: "Cape Verde", code: "cv" },
    { pais: "Cayman Islands", code: "ky" },
    { pais: "Central African Republic", code: "cf" },
    { pais: "Chad", code: "td" },
    { pais: "Chile", code: "cl" },
    { pais: "China", code: "cn" },
    { pais: "Colombia", code: "co" },
    { pais: "Comoros", code: "km" },
    { pais: "Congo", code: "cg" },
    { pais: "Costa Rica", code: "cr" },
    { pais: "Croatia", code: "hr" },
    { pais: "Cuba", code: "cu" },
    { pais: "Cyprus", code: "cy" },
    { pais: "Czech Republic", code: "cz" },
    { pais: "Denmark", code: "dk" },
    { pais: "Djibouti", code: "dj" },
    { pais: "Dominica", code: "dm" },
    { pais: "Dominican Republic", code: "do" },
    { pais: "DR Congo", code: "cd" },
    { pais: "Ecuador", code: "ec" },
    { pais: "Egypt", code: "eg" },
    { pais: "El Salvador", code: "sv" },
    { pais: "Equatorial Guinea", code: "gq" },
    { pais: "Eritrea", code: "er" },
    { pais: "Estonia", code: "ee" },
    { pais: "Eswatini", code: "sz" },
    { pais: "Ethiopia", code: "et" },
    { pais: "Fiji", code: "fj" },
    { pais: "Finland", code: "fi" },
    { pais: "France", code: "fr" },
    { pais: "French Polynesia", code: "pf" },
    { pais: "Gabon", code: "ga" },
    { pais: "Gambia", code: "gm" },
    { pais: "Georgia", code: "ge" },
    { pais: "Germany", code: "de" },
    { pais: "Ghana", code: "gh" },
    { pais: "Greece", code: "gr" },
    { pais: "Grenada", code: "gd" },
    { pais: "Guatemala", code: "gt" },
    { pais: "Guinea", code: "gn" },
    { pais: "Guyana", code: "gy" },
    { pais: "Haiti", code: "ht" },
    { pais: "Honduras", code: "hn" },
    { pais: "Hong Kong", code: "hk" },
    { pais: "Hungary", code: "hu" },
    { pais: "Iceland", code: "is" },
    { pais: "India", code: "in" },
    { pais: "Indonesia", code: "id" },
    { pais: "Iran", code: "ir" },
    { pais: "Iraq", code: "iq" },
    { pais: "Ireland", code: "ie" },
    { pais: "Israel", code: "il" },
    { pais: "Italy", code: "it" },
    { pais: "Ivory Coast", code: "ci" },
    { pais: "Jamaica", code: "jm" },
    { pais: "Japan", code: "jp" },
    { pais: "Jersey", code: "je" },
    { pais: "Jordan", code: "jo" },
    { pais: "Kazakhstan", code: "kz" },
    { pais: "Kenya", code: "ke" },
    { pais: "Kiribati", code: "ki" },
    { pais: "Kosovo", code: "xk" },
    { pais: "Kuwait", code: "kw" },
    { pais: "Kyrgyzstan", code: "kg" },
    { pais: "Laos", code: "la" },
    { pais: "Latvia", code: "lv" },
    { pais: "Lebanon", code: "lb" },
    { pais: "Lesotho", code: "ls" },
    { pais: "Liberia", code: "lr" },
    { pais: "Libya", code: "ly" },
    { pais: "Liechtenstein", code: "li" },
    { pais: "Lithuania", code: "lt" },
    { pais: "Luxembourg", code: "lu" },
    { pais: "Macau", code: "mo" },
    { pais: "Macedonia", code: "mk" },
    { pais: "Madagascar", code: "mg" },
    { pais: "Malawi", code: "mw" },
    { pais: "Malaysia", code: "my" },
    { pais: "Maldives", code: "mv" },
    { pais: "Mali", code: "ml" },
    { pais: "Malta", code: "mt" },
    { pais: "Marshall Islands", code: "mh" },
    { pais: "Mauritania", code: "mr" },
    { pais: "Mauritius", code: "mu" },
    { pais: "Mexico", code: "mx" },
    { pais: "Micronesia", code: "fm" },
    { pais: "Moldova", code: "md" },
    { pais: "Monaco", code: "mc" },
    { pais: "Mongolia", code: "mn" },
    { pais: "Montenegro", code: "me" },
    { pais: "Morocco", code: "ma" },
    { pais: "Mozambique", code: "mz" },
    { pais: "Myanmar", code: "mm" },
    { pais: "Namibia", code: "na" },
    { pais: "Nauru", code: "nr" },
    { pais: "Nepal", code: "np" },
    { pais: "Netherlands", code: "nl" },
    { pais: "New Zealand", code: "nz" },
    { pais: "Nicaragua", code: "ni" },
    { pais: "Niger", code: "ne" },
    { pais: "Nigeria", code: "ng" },
    { pais: "North Korea", code: "kp" },
    { pais: "Norway", code: "no" },
    { pais: "Oman", code: "om" },
    { pais: "Pakistan", code: "pk" },
    { pais: "Palau", code: "pw" },
    { pais: "Panama", code: "pa" },
    { pais: "Papua New Guinea", code: "pg" },
    { pais: "Paraguay", code: "py" },
    { pais: "Peru", code: "pe" },
    { pais: "Philippines", code: "ph" },
    { pais: "Poland", code: "pl" },
    { pais: "Portugal", code: "pt" },
    { pais: "Puerto Rico", code: "pr" },
    { pais: "Qatar", code: "qa" },
    { pais: "Romania", code: "ro" },
    { pais: "Russia", code: "ru" },
    { pais: "Rwanda", code: "rw" },
    { pais: "Samoa", code: "ws" },
    { pais: "San Marino", code: "sm" },
    { pais: "Saudi Arabia", code: "sa" },
    { pais: "Senegal", code: "sn" },
    { pais: "Serbia", code: "rs" },
    { pais: "Seychelles", code: "sc" },
    { pais: "Sierra Leone", code: "sl" },
    { pais: "Singapore", code: "sg" },
    { pais: "Slovakia", code: "sk" },
    { pais: "Slovenia", code: "si" },
    { pais: "Solomon Islands", code: "sb" },
    { pais: "Somalia", code: "so" },
    { pais: "South Africa", code: "za" },
    { pais: "South Korea", code: "kr" },
    { pais: "Spain", code: "es" },
    { pais: "Sri Lanka", code: "lk" },
    { pais: "Sudan", code: "sd" },
    { pais: "Suriname", code: "sr" },
    { pais: "Sweden", code: "se" },
    { pais: "Switzerland", code: "ch" },
    { pais: "Syria", code: "sy" },
    { pais: "Taiwan", code: "tw" },
    { pais: "Tajikistan", code: "tj" },
    { pais: "Tanzania", code: "tz" },
    { pais: "Thailand", code: "th" },
    { pais: "Timor-Leste", code: "tl" },
    { pais: "Togo", code: "tg" },
    { pais: "Tonga", code: "to" },
    { pais: "Tunisia", code: "tn" },
    { pais: "Turkey", code: "tr" },
    { pais: "Turkmenistan", code: "tm" },
    { pais: "Tuvalu", code: "tv" },
    { pais: "Uganda", code: "ug" },
    { pais: "Ukraine", code: "ua" },
    { pais: "United Arab Emirates", code: "ae" },
    { pais: "United Kingdom", code: "gb" },
    { pais: "United States of America", code: "us" },
    { pais: "Uruguay", code: "uy" },
    { pais: "Uzbekistan", code: "uz" },
    { pais: "Vanuatu", code: "vu" },
    { pais: "Vatican", code: "va" },
    { pais: "Venezuela", code: "ve" },
    { pais: "Vietnam", code: "vi" },
    { pais: "World", code: "wo" },
    { pais: "Yemen", code: "ye" },
    { pais: "Zambia", code: "zm" },
    { pais: "Zimbabwe", code: "zw" }
];

const handlePaisChange = (e) => {
  const nuevoPais = e.target.value;
  onPaisChange(nuevoPais);
};

  return (
   
      <Form.Group
        className="mb-3 d-flex justify-content-around "
        controlId="exampleForm.ControlInput2"
      >
        <Form.Label> Selecionar un Pais:</Form.Label>
        <Form.Select aria-label="Default select example" className="w-75" onChange={handlePaisChange}>
          {countries.map((country, index) => (
            <option key={index} value={country.code}>
              {country.pais}
            </option>
          ))}
        </Form.Select>
      </Form.Group>
    
  );
};

export default SelectPaises;
